# FROM apache/airflow:2.6.3
# RUN airflow db init

# ENV AIRFLOW__CORE__EXECUTOR=LocalExecutor
# USER airflow
# FROM python:3.12.8-bookworm

# WORKDIR /app

# RUN apt-get install libpq-dev

# COPY . .
